// check: VerificationError { kind: FunctionDefinition, idx: 1, err: NegativeStackSizeInsideBlock(0, 3) }

module Test {
    resource T { }

    public new(): R#Self.T {
        return T { };
    }

    public test(i: &u64, x: R#Self.T): u64 * R#Self.T * bool {
        return *move(i), move(x);
    }

    public destroy(x: R#Self.T) {
        T { } = move(x);
        return;
    }
}

//! new-transaction

import {{default}}.Test;

main() {
    let i: u64;
    let t: R#Test.T;
    let a: u64;
    let b: bool;
    let x: R#Test.T;

    i = 0;
    t = Test.new();
    a, x, b = Test.test(&i, move(t));
    assert(move(a) == 0, 42);
    Test.destroy(move(x));
    assert(!move(b), 43);

    return;
}