// check: VerificationError { kind: FunctionDefinition, idx: 0, err: PositiveStackSizeAtBlockEnd(0) }

module Test {
    resource T { }

    public new(): R#Self.T {
        return T { };
    }

    public test(i: &u64, x: R#Self.T): u64 * R#Self.T * bool {
        return *move(i), move(x), false;
    }

    public destroy(x: R#Self.T) {
        T { } = move(x);
        return;
    }
}

//! new-transaction

import {{default}}.Test;
main() {
    let i: u64;
    let t: R#Test.T;
    let a: u64;
    let x: R#Test.T;

    i = 0;
    t = Test.new();
    a, x = Test.test(&i, move(t));
    assert(move(a) == 0, 42);
    Test.destroy(move(x));

    return;
}